apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # echo -n 'your_password' | base64
  POSTGRES_PASSWORD_INVENTORY: cHlkYmFzZTIwMjQ= 
  POSTGRES_PASSWORD_BILLING: cHlkYmFzZTIwMjQ=
  RABBITMQ_DEFAULT_USER: dXNlcg==
  RABBITMQ_DEFAULT_PASS: cGFzc3dvcmQ=
  # Base64 values for:
  # postgres_user: postgres
  # postgres_db: inventory_db / billing_db
  # These should all be base64 encoded strings