apiVersion: v1
kind: Secret
metadata:
  name: billing-database-secrets
  namespace: default
type: Opaque
stringData:
  postgres-user: $POSTGRES_USER_BILLING
  postgres-password: $POSTGRES_PASSWORD_BILLING
  postgres-db: $POSTGRES_DB_BILLING
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: billing-database-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-database-deployment
  namespace: default
  labels:
    app: billing-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-database
  template:
    metadata:
      labels:
        app: billing-database
    spec:
      containers:
      - name: billing-database-postgres
        image: $DOCKER_USER/billing-database:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
          name: postgresdb
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: billing-database-secrets
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: billing-database-secrets
              key: postgres-password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: billing-database-secrets
              key: postgres-db
        volumeMounts:
        - name: billing-database-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: billing-database-storage
        persistentVolumeClaim:
          claimName: billing-database-pvc
---

apiVersion: v1
kind: Service
metadata:
  name: billing-database-service
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: billing-database