apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: billing-app
  labels:
    app: billingapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billingapp
  template:
    metadata:
      labels:
        app: billingapp
    spec:
      containers:
        - name: billing-app
          image: isayen/billing-app:v1.0
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          env:
            - name: BILLING_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: billing-app-secrets
                  key: url


            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: username

            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: password

            - name: RABBITMQ_VHOST
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: vhost

            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: api-gateway-secrets
                  key: rabbitmq-host

            - name: RABBITMQ_PORT
              valueFrom:
                secretKeyRef:
                  name: api-gateway-secrets
                  key: rabbitmq-port

            - name: RABBITMQ_QUEUE
              valueFrom:
                secretKeyRef:
                  name: api-gateway-secrets
                  key: rabbitmq-queue
          volumeMounts:
            - name: billing-app-data
              mountPath: /var/lib/billing-app/data
  serviceName: billing-app-service
  volumeClaimTemplates:
    - metadata:
        name: billing-app-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
            
--- 

apiVersion: v1
kind: Service
metadata:
  name: billing-app-service
spec:
  clusterIP: None
  selector:
    app: billingapp

---

apiVersion: v1
kind: Secret
metadata:
  name: billing-app-secrets
type: Opaque
stringData:
  url: "$BILLING_DATABASE_URL"