apiVersion: v1
kind: Secret
metadata:
  name: inventory-app-secrets
  namespace: default
type: Opaque
stringData:
  postgres-user: "$POSTGRES_USER_INVENTORY"
  postgres-password: "$POSTGRES_PASSWORD_INVENTORY"
  postgres-db: "$POSTGRES_DB_INVENTORY"
  db-url: "$INVENTORY_DATABASE_URL"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-app-deployment
  namespace: default
  labels:
    app: inventory-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-app
  template:
    metadata:
      labels:
        app: inventory-app
    spec:
      containers:
      - name: inventory-app
        image: "$DOCKER_USER/inventory-app:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: $INVENTORY_PORT 
          name: http
        env:
        - name: DB_HOST
          value: "$INVENTORY_DB_HOST" 
        - name: DB_PORT
          value: "$INVENTORY_DB_PORT" 
          
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: inventory-app-secrets
              key: postgres-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: inventory-app-secrets
              key: postgres-password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: inventory-app-secrets
              key: postgres-db
        - name: INVENTORY_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: inventory-app-secrets
              key: db-url

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: $INVENTORY_APP_HOST 
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: $INVENTORY_PORT
      targetPort: $INVENTORY_PORT
  selector:
    app: inventory-app
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: inventory-app-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: inventory-app-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60 