apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-app
  labels:
    app: invapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invapp
  template:
    metadata:
      labels:
        app: invapp
    spec:    
      containers:
        - name: inventory-app
          image: isayen/inventory-app:v1.0
          ports: 
            - containerPort: $INVENTORY_PORT
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          env:
            - name: INVENTORY_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: inventory-app-secrets
                  key: url
            - name: INVENTORY_PORT
              valueFrom:
                secretKeyRef:
                  name: inventory-app-secrets
                  key: port
            - name: INVENTORY_HOST
              valueFrom:
                secretKeyRef:
                  name: inventory-app-secrets
                  key: host

---

apiVersion: v1
kind: Service
metadata:
  name: inventory-app-service
spec:
  type: NodePort
  selector: 
    app: invapp
  ports:
    - port: $INVENTORY_PORT
      targetPort: $INVENTORY_PORT

--- 

apiVersion: v1
kind: Secret
metadata:
  name: inventory-app-secrets
type: Opaque
stringData:
  url: "$INVENTORY_DATABASE_URL"
  port: "$INVENTORY_PORT"
  host: "$INVENTORY_HOST_INTERFACE"

--- 

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: inventory-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: invapp
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60