apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
stringData:
  RABBITMQ_USER: "crud-master"
  RABBITMQ_PASS: "crud-master"
  RABBITMQ_VHOST: "/"
  RABBITMQ_HOST: "192.168.56.11"
  RABBITMQ_PORT: "5672"
  RABBITMQ_QUEUE: "billing_queue"
